name: Install MLIR

on:
  workflow_dispatch:
  workflow_call:

jobs:
  install-mlir:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: Check MLIR Build cache
      id: cache-mlir-build
      uses: actions/cache@v2
      with:
        path: llvm-project/build
        key: ${{ runner.os }}-mlir-commit-67760d7

    - name: Install dependencies
      if: steps.cache-mlir-build.outputs.cache-hit != 'true'
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build

    - name: Build MLIR
      if: steps.cache-mlir-build.outputs.cache-hit != 'true'
      run: |
        mkdir llvm-project/build
        cd llvm-project/build
        cmake -G Ninja ../llvm -DLLVM_ENABLE_PROJECTS=mlir -DLLVM_TARGETS_TO_BUILD="host" -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=ON
        ninja
      
